table Tbl_orders
	lineageTag: 44452e4b-b32f-49ab-84f8-7a1c2ff26fc9

	column Order_ID
		dataType: string
		lineageTag: d5c03bb0-7f52-4d5b-9156-a8999c23c556
		summarizeBy: none
		sourceColumn: Order_ID

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e8c6bb51-039c-4b4e-9e46-eb5adfe6a774
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Customer_Email
		dataType: string
		lineageTag: 22bd3ed0-8b89-4e74-b558-19561276695b
		summarizeBy: none
		sourceColumn: Customer_Email

		annotation SummarizationSetBy = Automatic

	column Shipping_Country
		dataType: string
		lineageTag: 11ef0870-4453-4eaf-b553-9aa1eee6d676
		summarizeBy: none
		sourceColumn: Shipping_Country

		annotation SummarizationSetBy = Automatic

	column Product_SKU
		dataType: string
		lineageTag: 599dad6d-839d-4b48-b36f-8df3fac905e4
		summarizeBy: none
		sourceColumn: Product_SKU

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: ec380df3-1b3f-49e8-8222-f41c92154af3
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		lineageTag: 71fb2a19-b66a-40dc-be7a-2e85f502f7a5
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Return_Status
		dataType: string
		lineageTag: 599d551f-7983-47e9-9885-afcd36ddcef3
		summarizeBy: none
		sourceColumn: Return_Status

		annotation SummarizationSetBy = Automatic

	partition Tbl_orders = m
		mode: import
		source =
				let
				    Źródło = Excel.Workbook(File.Contents("C:\Users\barte\Downloads\Ecom_Profitability_Engine_Data_v1.0.xlsx"), null, true),
				    Tbl_orders_Table = Źródło{[Item="Tbl_orders",Kind="Table"]}[Data],
				    #"Zmieniono typ" = Table.TransformColumnTypes(Tbl_orders_Table,{{"Order_ID", type text}, {"Order_Date", type date}, {"Customer_Email", type text}, {"Shipping_Country", type text}, {"Product_SKU", type text}, {"Quantity", Int64.Type}, {"Unit_Price", type number}, {"Return_Status", type text}}),
				    #"Przefiltrowano wiersze" = Table.SelectRows(#"Zmieniono typ", each [Order_ID] <> null and [Order_ID] <> ""),
				    #"Przefiltrowano wiersze1" = Table.SelectRows(#"Przefiltrowano wiersze", each [Product_SKU] <> null and [Product_SKU] <> "")
				in
				    #"Przefiltrowano wiersze1"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

